services:
  remote-app:
    container_name: htpc-remote-demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DEMO_MODE: ${NEXT_PUBLIC_DEMO_MODE:-false}
    environment:
      NEXT_PUBLIC_DEMO_MODE: ${NEXT_PUBLIC_DEMO_MODE:-false}
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "${HTPC_REMOTE_BIND_IP:-0.0.0.0}:3000:3000"
    networks:
      - htpc-remote

networks:
  htpc-remote:
    name: htpc-remote
    driver: bridge
