import {
  DENON_HTTP_COMMAND_URL,
  DENON_HTTP_QUERY_URL,
  DENON_IP,
  GAMESTREAM_EVENTGHOST_URL,
  HTPC_EVENTGHOST_URL,
  PLATFORM,
  ROKU_URL,
} from "@/constants/environment";
import { URL_ENCODED_SYMBOLS } from "@/constants/encoding";
import {
  ClickType,
  DenonKeystroke,
  KEYSTROKE,
  PcKeystroke,
  RemoteType,
  REMOTE_INDEX,
  RokuKeystroke,
  SYSTEM_KEYS,
} from "@/constants/remotes";
import {
  AUDIO_MODES_FOR_SELECT as PC_AUDIO_MODES,
  DISPLAY_MODES_FOR_SELECT,
} from "@/components/RemotePanels/PC/pcConstants";
import {
  AUDIO_MODES_FOR_SELECT as DENON_AUDIO_MODES,
  DOLBY_MODES,
  DTS_MODES,
  DENON_HTTP_COMMANDS,
  DENON_INPUTS,
  DENON_REMOTE_META,
  DENON_SOUND_MODES,
  DENON_STATE_DEFAULTS,
} from "@/components/RemotePanels/Denon/denonConstants";
import {
  ROKU_APPS,
  ROKU_POST_OPTIONS,
  ROKU_REMOTE_META,
  ROKU_STATE_DEFAULTS,
} from "@/components/RemotePanels/Roku/rokuConstants";
import { LIGHTSWITCHES, PLUGS } from "@/components/RemotePanels/SmartHome/smartHomeConstants";

export const REMOTE = RemoteType;
export { REMOTE_INDEX, URL_ENCODED_SYMBOLS, KEYSTROKE, SYSTEM_KEYS };
export const CLICK_TYPE = ClickType;
export const ROKU_REMOTE = RokuKeystroke;
export const PC_REMOTE = PcKeystroke;
export const DENON_REMOTE = DenonKeystroke;
export const AUDIO_MODES_FOR_SELECT = PC_AUDIO_MODES;

export {
  ROKU_URL,
  ROKU_APPS,
  ROKU_POST_OPTIONS,
  ROKU_STATE_DEFAULTS,
  PLATFORM,
  DENON_IP,
  DENON_INPUTS,
  DOLBY_MODES,
  DTS_MODES,
  DENON_SOUND_MODES,
  DENON_STATE_DEFAULTS,
  DENON_HTTP_COMMANDS,
  PC_AUDIO_MODES,
  DISPLAY_MODES_FOR_SELECT,
  DENON_AUDIO_MODES,
  PLUGS,
  LIGHTSWITCHES,
  HTPC_EVENTGHOST_URL,
  GAMESTREAM_EVENTGHOST_URL,
  DENON_HTTP_COMMAND_URL,
  DENON_HTTP_QUERY_URL,
  DENON_REMOTE_META,
  ROKU_REMOTE_META,
};

const Constants = {
  EVENTGHOST_URL: HTPC_EVENTGHOST_URL,
  ROKU_URL,
  DENON_HTTP_URL: DENON_HTTP_COMMAND_URL,
  ROKU_POST_OPTIONS,
  REMOTE,
  REMOTE_INDEX,
  URL_ENCODED_SYMBOLS,
  ROKU_APPS,
  AUDIO_MODES: PC_AUDIO_MODES,
  DISPLAY_MODES: DISPLAY_MODES_FOR_SELECT,
  KEYSTROKE,
  SYSTEM_KEYS,
  DENON_HTTP_COMMANDS,
};

export default Constants;
