#!/usr/bin/env bash
set -euo pipefail

CARD="alsa_card.pci-0000_00_1f.3"  # from `pactl list cards short`

mode="${1:-}"

usage() {
  cat <<EOF
Usage: htpc-audio MODE

MODE:
  analog-stereo      - Onboard analog stereo (PC speakers / headphones)
  hdmi-stereo        - HDMI stereo (2.0 PCM) to DENON AVR
  surround51-hdmi    - HDMI surround 5.1 PCM to DENON AVR
  surround71-hdmi    - HDMI surround 7.1 PCM to DENON AVR

EOF
  exit 1
}

case "$mode" in
  analog-stereo)
    pactl set-card-profile "$CARD" output:analog-stereo
    ;;

  hdmi-stereo)
    pactl set-card-profile "$CARD" output:hdmi-stereo
    ;;

  surround51-hdmi)
    pactl set-card-profile "$CARD" output:hdmi-surround
    ;;

  surround71-hdmi)
    pactl set-card-profile "$CARD" output:hdmi-surround71
    ;;

  *)
    usage
    ;;
esac
